import Link from 'next/link';
import { notFound } from 'next/navigation';

const data: Record<string, any> = {
  masterpos: {
    name:'MasterPOS', tag:'RESTAURANT MANAGEMENT SOFTWARE', title:'Run your restaurant with confidence.', desc:'A complete restaurant management platform built around the real flow of a busy restaurant — from table ordering and KOT to billing, inventory, purchasing, reports and staff management.', image:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1600&q=90',
    features:[['◫','Table & Order Management','Manage tables, open orders, transfers, merges and split bills from one live screen.'],['◇','KOT & Kitchen Flow','Send orders from waiter phones to the server and route KOTs to the right kitchen or bar printer.'],['₹','Fast Billing','Handle counter billing, held bills, payments, discounts, returns and end-of-session cash control.'],['▤','Inventory & Purchasing','Track recipes, stock, purchases, wastage, suppliers and item movement without leaving the POS.'],['◌','Customer Management','Keep visit history, customer balances, loyalty information and useful customer records.'],['↗','Reports & Reconciliation','Daily, monthly and product-level sales reports plus cash/bank and party reconciliation.']],
    steps:[['01','Open table','The waiter opens a table on a phone or the cashier starts a counter order.'],['02','Build order','Items are added with modifiers, notes and quantities.'],['03','Send KOT','The server saves the order and the print service sends KOTs to the correct printer.'],['04','Serve & update','Additional items can be added while the same table remains open.'],['05','Bill & pay','Cashier opens the live order, applies discounts/tax and records payment.'],['06','Close','The bill closes and the transaction is included in session and business reports.']]
  },
  hotel: {
    name:'MPOS Hotel', tag:'HOTEL MANAGEMENT SOFTWARE', title:'One connected system for your hotel.', desc:'Bring reservations, front office, rooms, guest records, billing, housekeeping and hotel POS operations into one connected platform.', image:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=90',
    features:[['⌂','Front Office','See room status, arrivals, departures, occupied rooms and guest information at a glance.'],['◇','Reservations','Manage bookings, room types, rates, deposits, cancellations and availability.'],['▣','Check-in & Check-out','Move guests through a clean front-desk workflow with folios and payment handling.'],['♢','Housekeeping','Track room cleaning, inspection and room status changes across the property.'],['₹','Hotel Billing','Combine room charges and outlet charges into guest folios and process payments.'],['↗','Reports','Monitor occupancy, revenue, room sales, outlet sales and operational performance.']],
    steps:[['01','Reservation','Create or receive a reservation and assign the appropriate room type.'],['02','Arrival','Confirm guest details, deposit and room, then complete check-in.'],['03','Stay','Post room, restaurant or other approved charges to the guest folio.'],['04','Housekeeping','Room status updates keep front office and housekeeping synchronized.'],['05','Checkout','Review the folio, settle payment and close the guest stay.'],['06','Report','Closed transactions flow into hotel and business reports automatically.']]
  },
  spa: {
    name:'MPOS Spa', tag:'SPA, SALON & PARLOR SOFTWARE', title:'Make every appointment feel effortless.', desc:'Manage bookings and walk-ins, assign therapists, reserve rooms, run services and packages, and complete billing through one elegant workflow.', image:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1600&q=90',
    features:[['◷','Appointments & Walk-ins','See the day by time, service and staff, while keeping walk-in customers moving quickly.'],['♙','Therapist Assignment','Assign the right staff member to a service and track availability without double booking.'],['◇','Room / Bed Management','Use rooms like restaurant tables — open a service, move it, update it and close it.'],['✦','Services & Packages','Create service menus, durations, prices, packages, add-ons and staff-linked services.'],['₹','Billing','Bill completed services, packages, products and other charges with clean payment tracking.'],['◌','Customer History','Keep visits, services, packages, preferences and balances together for better service.']],
    steps:[['01','Book or walk in','Find the appointment or create a new walk-in customer.'],['02','Choose service','Select the requested service and scheduled time from the menu.'],['03','Assign staff','Manager or receptionist assigns a therapist or service staff member.'],['04','Assign room','Open an available room or bed and connect it to the active service.'],['05','Complete service','Staff finishes the service and marks it completed.'],['06','Bill & close','Cashier bills the active room/service, records payment and closes the session.']]
  },
  banquet: {
    name:'MPOS Banquet', tag:'BANQUET & EVENT MANAGEMENT', title:'Turn every event into a well-managed experience.', desc:'Manage halls, event enquiries, bookings, packages, menus, customer commitments, billing and event-day operations from one place.', image:'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=90',
    features:[['◇','Hall & Venue Management','Keep availability and booking status clear across halls, rooms and event spaces.'],['◷','Event Bookings','Capture event date, time, guest count, client details, deposits and booking status.'],['✦','Packages & Menus','Build reusable event packages with food, beverages, services and optional extras.'],['₹','Quotation & Billing','Move from enquiry to quotation, advance payments, final billing and settlement.'],['▤','Event Operations','Track assigned staff, service requirements, notes and event-day changes.'],['↗','Reports','Review bookings, revenue, outstanding balances and event performance.']],
    steps:[['01','Enquiry','Record the client, event type, date, expected guests and requirements.'],['02','Availability','Check the requested hall and time against existing bookings.'],['03','Package','Build the event package, menu and additional services.'],['04','Confirm','Record advance/deposit and confirm the booking.'],['05','Event day','Manage changes and operational notes while the event is active.'],['06','Settlement','Complete final billing, payment and close the event.']]
  },
  'hr-payroll': {
    name:'MPOS HR & Payroll', tag:'INTEGRATED OR STANDALONE', title:'People management without the paperwork.', desc:'A practical HR and payroll system that can run inside your MPOS business software or independently for organizations that only need HR and payroll.', image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=90',
    features:[['♙','Employee Profiles','Centralize employee details, contracts, roles, departments and employment information.'],['◷','Attendance & Shifts','Manage attendance, shifts, late arrivals, absences and approved leave.'],['✦','Leave Management','Record leave requests, paid leave and leave balances with clear approval flow.'],['₹','Payroll Processing','Calculate salary with earnings, allowances, deductions, advances and attendance adjustments.'],['▤','Advances & Deductions','Track staff advances and recoveries with transparent records.'],['↗','Evaluation & Reports','Review attendance and performance indicators and generate payroll reports.']],
    steps:[['01','Employee setup','Create employees, salary structure, department and work schedule.'],['02','Attendance','Verify the monthly attendance record and approved leave.'],['03','Payroll inputs','Set allowances, paid leave, advances and approved deductions.'],['04','Calculate','Generate payroll from the verified attendance and salary structure.'],['05','Review','Check deductions, net salary and payment totals before release.'],['06','Release','Record salary payment through the selected cash/bank account and close payroll.']]
  }
};

export function generateStaticParams(){ return Object.keys(data).map(slug=>({slug})); }

export default async function ProductDetail({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const p=data[slug]; if(!p) notFound();
  return <>
    <header className="nav"><div className="nav-inner"><Link className="brand" href="/"><span className="brand-mark">M</span>MPOS</Link><nav><Link href="/">Home</Link><Link href="/products">Products</Link><Link href="/pricing">Pricing</Link><Link href="/contact">Contact</Link></nav><Link className="gold-btn" href="/contact">Book a Demo →</Link></div></header>
    <main>
      <section className="detail-hero"><div className="detail-copy"><div className="eyebrow">{p.tag}</div><h1>{p.title}</h1><p>{p.desc}</p><div className="actions"><Link className="gold-btn" href="/contact">Request a Demo →</Link><Link className="outline-btn" href="/products">← All Products</Link></div></div><div className="detail-image" style={{backgroundImage:`url(${p.image})`}}><span>MPOS • {p.name}</span></div></section>
      <section className="feature-section"><div className="eyebrow">WHAT YOU GET</div><h2>Everything your team<br/><em>needs to work better.</em></h2><div className="detail-grid">{p.features.map((f:string[],i:number)=><article key={i}><span>{f[0]}</span><h3>{f[1]}</h3><p>{f[2]}</p></article>)}</div></section>
      <section className="workflow"><div><div className="eyebrow light">HOW IT WORKS</div><h2>Designed around<br/><em>your daily workflow.</em></h2><p>MPOS connects each step so your staff spend less time moving between screens and more time serving customers.</p></div><div className="steps">{p.steps.map((s:string[],i:number)=><div key={i}><b>{s[0]}</b><strong>{s[1]}</strong><p>{s[2]}</p></div>)}</div></section>
      <section className="feature-section showcase"><div className="showcase-copy"><div className="eyebrow">ONE CONNECTED PLATFORM</div><h2>From the first action to the final report.</h2><p>Every completed transaction becomes part of the same business record. Managers get visibility, staff get simpler screens and owners get reliable information for decisions.</p><Link className="gold-btn" href="/contact">See MPOS in Action →</Link></div><div className="mockup"><div className="mock-top"><span>{p.name}</span><small>Today · Live</small></div><div className="mock-stats"><div><small>Today's sales</small><b>Rs. 184,650</b></div><div><small>Open items</small><b>24</b></div><div><small>Completed</small><b>86</b></div></div><div className="mock-chart"><span style={{height:'38%'}}></span><span style={{height:'52%'}}></span><span style={{height:'46%'}}></span><span style={{height:'72%'}}></span><span style={{height:'61%'}}></span><span style={{height:'84%'}}></span><span style={{height:'76%'}}></span><span style={{height:'94%'}}></span></div></div></section>
      <section className="detail-cta"><div><div className="eyebrow">READY TO GET STARTED?</div><h2>Let's build a better operation.</h2><p>Tell us about your business and we'll show you the workflow.</p></div><Link className="gold-btn" href="/contact">Request a Demo →</Link></section>
    </main>
  </>
}
