import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Products — Restaurant, Hotel, Spa, Banquet & HR Software | MPOS',
  description: 'Explore the MPOS product suite: restaurant management software, hotel management software, spa and salon software, banquet and event software, and standalone HR and payroll software.',
  alternates: { canonical: '/products/' },
};
const products=[['masterpos','MPOS Restaurant Management Software','Restaurant Management','Complete POS and restaurant operations from tables and KOT to billing, inventory and reports.'],['hotel','MPOS Hotel Management Software','Hotel Management','Front office, reservations, rooms, guests, billing, housekeeping and connected operations.'],['spa','MPOS Spa & Salon Management Software','Spa, Salon & Parlor','Appointments, walk-ins, therapists, rooms, services, packages, customers and billing.'],['banquet','MPOS Banquet & Event Management Software','Banquet & Events','Bookings, halls, packages, menus, client records, billing and event operations.'],['hr-payroll','MPOS HR & Payroll Software','Standalone or Integrated','Employee, attendance, leave, shifts and payroll management for MPOS businesses or standalone use.']];
export default function Products(){return <><header className="simple-header"><div className="simple-header-inner"><Link className="brand" href="/"><span className="brand-mark">M</span>MPOS</Link><nav><Link href="/">Home</Link><Link href="/products">Products</Link><Link href="/pricing">Pricing</Link><Link href="/contact">Contact</Link></nav><Link href="/" className="back">← Home</Link></div></header><main><section className="product-hero"><div className="eyebrow">MPOS PRODUCTS</div><h1>Purpose-built software<br/><em>for real operations.</em></h1><p>Choose the system that matches your business. Each product includes industry-specific workflows and can connect with MPOS HR & Payroll.</p></section><section className="all-products">{products.map(([slug,name,tag,desc],i)=><Link className="big-product" href={`/products/${slug}`} key={slug}><div className="number">0{i+1}</div><div><span>{tag}</span><h2>{name}</h2><p>{desc}</p><b>Explore features →</b></div><div className="round-arrow">↗</div></Link>)}</section></main></>}
